server:
  port: 9002

spring:
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp15ol5phrs6k3x6n2o.mysql.rds.aliyuncs.com:3306/iprp_dev?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: iprp_dev
      password: dev@2020
      stat-view-servlet:
        login-password: B1ockch@in
        login-username: admin
